import { Product } from '../entity/Product';
import { categorySeed } from './category';

export const productSeed: Product[] = [
  {
    id: 1,
    status: 'ACTIVE',
    category: categorySeed[0],
    description: 'IPhone 13 Description',
    imageUrl: '',
    name: 'IPhone 13',
    price: 1000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    status: 'ACTIVE',
    category: categorySeed[0],
    description: 'IPhone 13 Pro max Description',
    imageUrl: '',
    name: 'IPhone 13 Pro Max',
    price: 2000000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    status: 'ACTIVE',
    category: categorySeed[1],
    description: 'Laptop Dell Description',
    imageUrl: '',
    name: 'Laptop Dell',
    price: 20000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    status: 'ACTIVE',
    category: categorySeed[1],
    description: 'Laptop Lenovo Description',
    imageUrl: '',
    name: 'Laptop Lenovo',
    price: 30000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    status: 'ACTIVE',
    category: categorySeed[2],
    description: 'TV Samsung Description',
    imageUrl: '',
    name: 'TV Samsung',
    price: 50000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    status: 'ACTIVE',
    category: categorySeed[2],
    description: 'Tv Dell For Gaming Description',
    imageUrl: '',
    name: 'Tv Dell For Gaming',
    price: 60000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    status: 'ACTIVE',
    category: categorySeed[3],
    description: "Women Product That i Don't Know Description",
    imageUrl: '',
    name: "Women Product That i Don't Know",
    price: 500000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
